name: Copy Files to Blog Repository

on:
  push:
    branches:
      - main  # O la rama que desees monitorizar

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4  # Actualizamos a la última versión

      - name: Checkout Destination Repository
        uses: actions/checkout@v4  # Actualizamos a la última versión
        with:
          repository: schmittnieto/schmittnieto.github.io
          path: blog_repo
          token: ${{ secrets.GH_PAT }}

      - name: Copy Files
        run: |
          rsync -av --exclude='.git' ./ blog_repo/assets/post/2024-10-04-Azure-Stack-HCI-Demolab/ --exclude=blog_repo
          
      - name: Commit and Push Changes
        working-directory: blog_repo
        run: |
          git config user.name "schmittnieto"
          git config user.email "tu-email@ejemplo.com"
          git add .
          git commit -m "Update files from AzSHCI repository"
          git push origin main
